### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ramavaidya15** [ramavaidya15/giraffe#3]
Hello @shreyventure , this project looks bland without any images. Can you help me add a few?

**Comment by shreyventure** [comment]
# Okay boss!

**Comment by shreyventure** [comment]
# Okay boss (pt. 2)

**Comment by shreyventure** [comment]
> Hello @shreyventure , this project looks bland without any images. Can you help me add a few?

# okay boss (pt. 3)

**Comment by ramavaidya15** [comment]
> > Hello @shreyventure , this project looks bland without any images. Can you help me add a few?
> 
> # okay boss (pt. 3)

**Comment by ramavaidya15** [comment]
> > > Hello @shreyventure , this project looks bland without any images. Can you help me add a few?
> > 
> > 
> > # okay boss (pt. 3)

fastttttt

**Comment by shreyventure** [comment]
> > > > Hello @shreyventure , this project looks bland without any images. Can you help me add a few?
> > > 
> > > 
> > > # okay boss (pt. 3)
> 
> fastttttt

# Done

**Comment by ramavaidya15** [comment]
# Thanks boss
